# Generated by Django 4.2.30 on 2026-08-11 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('merchant_invoice_id', models.CharField(help_text='Merchant reference sent to the gateway, e.g. PINV-4F2A1C', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, default='', help_text='Gateway-side id: bKash paymentID/trxID or Nagad payment_ref_id', max_length=64)),
                ('raw_callback', models.JSONField(blank=True, default=dict, help_text='Raw callback payload for audit/debugging')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_167f0e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_payment_order_item'),
        ),
    ]
