# Generated by Django 4.2.30 on 2026-08-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Gateway-side id: bKash paymentID/trxID or Nagad payment_ref_id', max_length=64),
        ),
    ]
