# Generated by Django 4.2.30 on 2026-08-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layout_json', models.JSONField(default=dict, help_text='Defines default section order and block placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL endpoint, e.g., 'dashboard', 'research-ai'", unique=True)),
                ('page_type', models.CharField(choices=[('global', 'Global Page'), ('department', 'Department Hub'), ('club', 'Club Page'), ('notice', 'Notice Page')], default='global', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Theme style overrides')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.pagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('content_html', models.TextField(blank=True)),
                ('style_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.editablepage')),
            ],
            options={
                'unique_together': {('page', 'element_id')},
            },
        ),
    ]
