# Generated by Django 4.2.30 on 2026-08-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mealticket_mealsubscription_transportbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealticket',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, help_text='When the cafeteria counter redeemed this ticket', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('academic', 'Academic'), ('meal', 'Meal System'), ('transport', 'Transport'), ('medical', 'Medical'), ('club', 'Club & Events')], max_length=50),
        ),
    ]
