# Generated by Django 4.2.30 on 2026-08-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_mealticket_redeemed_at_alter_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code, e.g. CS101', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('TEX', 'Textile Engineering'), ('IPE', 'Industrial & Production Engineering'), ('FDAE', 'Fashion Design & Technology'), ('EEE', 'Electrical & Electronic Engineering')], max_length=10)),
                ('semester', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('urgent', 'Urgent'), ('academic', 'Academic'), ('event', 'Event'), ('general', 'General')], max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Drafts are stored but never shown to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Staff member who authored this notice', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course_materials/')),
                ('file_type', models.CharField(blank=True, default='', help_text='Optional override; falls back to the file extension', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
