# Generated by Django 4.2.30 on 2026-08-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_transport_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busschedule',
            options={},
        ),
    ]
