# Generated by Django 4.2.30 on 2026-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_busschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('html', 'Rich Text / HTML'), ('faq', 'FAQ Accordion'), ('stats', 'Stats Counter Grid'), ('testimonials', 'Testimonial Slider'), ('cta', 'CTA Section')], db_index=True, default='html', help_text='Rendering strategy: raw HTML or a structured component', max_length=20),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data for faq / stats / testimonials / cta blocks — see BLOCK_SCHEMAS'),
        ),
    ]
