# Generated by Django 4.2.30 on 2026-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contentblock_block_type_contentblock_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='notify_meals',
            field=models.BooleanField(default=True, help_text='Receive meal ticket notifications'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='notify_medical',
            field=models.BooleanField(default=True, help_text='Receive medical appointment notifications'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='notify_notices',
            field=models.BooleanField(default=True, help_text='Receive official notice alerts'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='notify_transport',
            field=models.BooleanField(default=True, help_text='Receive transport booking notifications'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='timezone',
            field=models.CharField(choices=[('Asia/Dhaka', 'Bangladesh (BST, UTC+6)'), ('Asia/Kolkata', 'India (IST, UTC+5:30)'), ('UTC', 'Coordinated Universal Time'), ('America/New_York', 'Eastern Time (US & Canada)'), ('Europe/London', 'London (GMT/BST)')], default='Asia/Dhaka', help_text='Display timezone for timestamps', max_length=50),
        ),
    ]
