# Generated by Django — EditablePage lifecycle fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contentblock_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablepage',
            name='seo_description',
            field=models.TextField(
                blank=True,
                help_text='Meta description used for search-engine snippets',
            ),
        ),
        migrations.AddField(
            model_name='editablepage',
            name='show_in_nav',
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text='Show a link to this page in the top navigation Pages menu',
            ),
        ),
    ]
