# Generated by Django 4.2.30 on 2026-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('html', 'Text Block'), ('hero', 'Hero Header'), ('features', 'Feature Cards Grid'), ('split', 'Text & Image Split'), ('links', 'Link Hub'), ('staff', 'Staff Grid'), ('faq', 'FAQ Accordion'), ('stats', 'Stats Counter Grid'), ('testimonials', 'Testimonial Slider'), ('cta', 'CTA Section')], db_index=True, default='html', help_text='Rendering strategy: raw HTML or a structured component', max_length=20),
        ),
    ]
