# Generated by Django 4.2.30 on 2026-08-11 02:25

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def backfill_existing_items_as_paid(apps, schema_editor):
    """Rows created before payment gating were all issued instantly (free
    flow) — record them as paid/entitled with their original issuance time."""
    TransportBooking = apps.get_model('core', 'TransportBooking')
    MealTicket = apps.get_model('core', 'MealTicket')
    TransportBooking.objects.update(payment_status='paid', paid_at=F('booked_at'))
    MealTicket.objects.update(payment_status='paid', paid_at=F('claimed_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('core', '0022_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was activated (instant claim or payment confirmed)', null=True),
        ),
        migrations.AddField(
            model_name='mealticket',
            name='payment_order',
            field=models.OneToOneField(blank=True, help_text='The payment order that activated this ticket (paid flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_ticket', to='payments.paymentorder'),
        ),
        migrations.AddField(
            model_name='mealticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid / entitled'), ('failed', 'Payment failed')], db_index=True, default='pending', help_text='Paid-flow gating: pending until the gateway SUCCESS callback; instant claims record paid.', max_length=10),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When this booking was activated (instant book or payment confirmed)', null=True),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='payment_order',
            field=models.OneToOneField(blank=True, help_text='The payment order that activated this booking (paid flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_booking', to='payments.paymentorder'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid / entitled'), ('failed', 'Payment failed')], db_index=True, default='pending', help_text='Paid-flow gating: pending until the gateway SUCCESS callback; instant bookings record paid.', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealticket',
            name='ticket_token',
            field=models.CharField(blank=True, help_text='Format e.g. #MEAL-XXXX — generated when the ticket is activated (instant claim or payment confirmed)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Boarding QR code — generated when the booking is activated (instant book or payment confirmed)', max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(backfill_existing_items_as_paid, migrations.RunPython.noop),
    ]
