# Generated by Django 4.2.30 on 2026-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='drive_content_link',
            field=models.URLField(blank=True, default='', help_text='Google Drive webContentLink (direct download) for this material'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='drive_view_link',
            field=models.URLField(blank=True, default='', help_text='Google Drive webViewLink for this lecture material'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='drive_content_link',
            field=models.URLField(blank=True, default='', help_text='Google Drive webContentLink (direct download) for this note'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='drive_view_link',
            field=models.URLField(blank=True, default='', help_text='Google Drive webViewLink for the exported copy of this note'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='course_materials/'),
        ),
    ]
