# Generated by Django 4.2.30 on 2026-08-12 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_sync_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Weekly schedule in the canonical {"days": [...]} shape')),
                ('source_name', models.CharField(blank=True, default='', help_text='Uploaded file name or "manual" when pasted as JSON', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('assignment', 'Assignment'), ('event', 'Event')], db_index=True, default='event', max_length=20)),
                ('event_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date', 'id'],
                'indexes': [models.Index(fields=['event_date', 'category'], name='core_academ_event_d_526996_idx')],
            },
        ),
    ]
