# Generated by Django 4.2.30 on 2026-08-12 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_seed_academic_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('academic', 'Academic'), ('meal', 'Meal System'), ('transport', 'Transport'), ('medical', 'Medical'), ('club', 'Club & Events'), ('report', 'Reports & Feedback')], max_length=50),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('facility', 'Facility'), ('technical', 'Technical'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Staff response / resolution notes shown to the student')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Student who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_report_user_id_411741_idx'), models.Index(fields=['status', '-created_at'], name='core_report_status_2f6592_idx')],
            },
        ),
    ]
