# Generated by Django 4.2.30 on 2026-08-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_alter_notification_category_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Club Manager'), ('executive', 'Club Executive'), ('president', 'Club President')], default='manager', max_length=20)),
                ('can_post_events', models.BooleanField(default=True, help_text='May publish events and announcements for the club')),
                ('can_manage_members', models.BooleanField(default=True, help_text='May approve/reject membership requests')),
                ('can_manage_finances', models.BooleanField(default=False, help_text='May verify payments and manage club funds')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive club accounts are locked out of the club workspace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['club__name', 'user__username'],
            },
        ),
    ]
