# Generated by Django 4.2.30 on 2026-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_clubaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('system', 'System Default')], default='system', help_text='Portal theme: light, dark, or follow the system preference', max_length=10),
        ),
    ]
