# Generated by Django 4.2 — Report severity, attachment, and Medical/General categories.

from django.db import migrations, models


def remap_legacy_category(apps, schema_editor):
    """Legacy rows stored with category ``other`` map to the new ``general`` label."""
    Report = apps.get_model('core', 'Report')
    Report.objects.filter(category='other').update(category='general')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_usernotificationpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(
                choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')],
                db_index=True,
                default='medium',
                help_text='Low / Medium / High / Critical impact of the issue',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(
                blank=True,
                help_text='Optional screenshot or supporting file (max 10 MB)',
                null=True,
                upload_to='reports/%Y/%m/',
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='attachment_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Original file name of the attachment for display',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(
                choices=[
                    ('academic', 'Academic'),
                    ('facility', 'Facility'),
                    ('medical', 'Medical'),
                    ('technical', 'Technical'),
                    ('general', 'General'),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.RunPython(remap_legacy_category, noop),
    ]
