# Generated by Django 4.2.30 on 2026-08-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(help_text='Email address the class QR code and attendance reports are sent to', max_length=254, unique=True)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Optional contact number', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive teachers are hidden from dispatch selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='core_attend_course__012204_idx',
            old_name='att_sess_course_created',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this teacher takes attendance for', related_name='teachers', to='core.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this teacher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.department'),
        ),
    ]
