# Generated by Django 4.2.30 on 2026-08-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline, e.g. "Severe Weather Warning"', max_length=200)),
                ('message', models.TextField(help_text='Detailed instructions shown to students')),
                ('severity_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, default='WARNING', max_length=20)),
                ('play_alarm_sound', models.BooleanField(default=False, help_text='Triggers the siren audio loop on student dashboards')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one alert is live at a time — the active emergency state')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When an admin cleared/resolved this alert', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='core_emerge_is_acti_629ae8_idx')],
            },
        ),
    ]
