# Generated by Django 4.2.30 on 2026-08-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Daily', help_text='Day label, e.g. Daily or a weekday (Sun, Mon, …)', max_length=20)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Morning Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Evening Snacks')], max_length=20)),
                ('items', models.TextField(help_text='Comma-separated menu items served for this meal')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('day', 'meal_type')},
            },
        ),
    ]
