# Generated by Django 4.2.30 on 2026-08-15 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_mealmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Brand name, e.g. Napa', max_length=120)),
                ('generic_name', models.CharField(blank=True, db_index=True, default='', help_text='Generic name, e.g. Paracetamol — drives substitute suggestions', max_length=120)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g. 500mg', max_length=60)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('ointment', 'Ointment'), ('injection', 'Injection'), ('other', 'Other')], default='tablet', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_prescription', models.BooleanField(default=False, help_text='Rx Required — needs an approved prescription to purchase')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, default='', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Restock warning threshold — stock at or below this is low')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Customer-facing order id, e.g. PO-A1B2C3', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('rx_verified', 'Rx Verified'), ('packaging', 'Packaging'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='placed', max_length=20)),
                ('hall_name', models.CharField(blank=True, default='', max_length=100)),
                ('room_no', models.CharField(blank=True, default='', max_length=40)),
                ('department', models.CharField(blank=True, default='', max_length=10)),
                ('delivery_instructions', models.CharField(blank=True, default='', max_length=300)),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('sslcommerz', 'SSLCommerz'), ('cod', 'Cash on Delivery / Pay at Medical Center')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cod', 'Pay on Delivery')], default='pending', max_length=20)),
                ('wallet_trx', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('meal', 'Meal Ticket'), ('tuition', 'Tuition'), ('event', 'Event'), ('transport', 'Transport'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, JPG or PNG of the prescription', upload_to='prescriptions/')),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, default='', help_text='Rejection reason', max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.medicineitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pharmacyorder')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
