# Generated by Django 4.2.30 on 2026-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_medicineitem_pharmacyorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('rocket', 'Rocket'), ('sslcommerz', 'SSLCommerz')], max_length=20),
        ),
    ]
