# Generated by Django 4.2.30 on 2026-08-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='visible',
            field=models.BooleanField(default=True, help_text='Show / hide this block on the live page (system-page sections like video feeds or chat boxes)'),
        ),
        migrations.AddField(
            model_name='editablepage',
            name='system_key',
            field=models.CharField(blank=True, help_text='Registered core system page key (home / study-corner / pharmacy / news / clubs) — set by the register_system_pages command', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('html', 'Text Block'), ('hero', 'Hero Header'), ('features', 'Feature Cards Grid'), ('split', 'Text & Image Split'), ('links', 'Link Hub'), ('staff', 'Staff Grid'), ('faq', 'FAQ Accordion'), ('stats', 'Stats Counter Grid'), ('testimonials', 'Testimonial Slider'), ('cta', 'CTA Section'), ('announcements', 'Quick Announcements'), ('notes', 'Notes Listing'), ('youtube', 'YouTube Search & Video Section'), ('chat', 'Study Assistant Chat Container'), ('category_nav', 'Category Navigation Strip'), ('promo', 'Hero Promo Banner'), ('brands', 'Top Brands Showcase'), ('products', 'Product Grid'), ('news_search', 'News Search Bar'), ('card_grid', 'Image Card Grid'), ('video_feed', 'YouTube Video Feed')], db_index=True, default='html', help_text='Rendering strategy: raw HTML or a structured component', max_length=20),
        ),
    ]
