# Generated by Django 4.2.30 on 2026-08-15 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_contentblock_visible_editablepage_system_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineitem',
            name='delivery_eta',
            field=models.CharField(blank=True, default='', help_text='Estimated delivery time shown on the product detail, e.g. 30-45 mins on campus', max_length=120),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='dosage_info',
            field=models.TextField(blank=True, default='', help_text='Dosage instructions'),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Medicine photo URL — rendered on the store card + detail modal', max_length=500),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='manufacturer',
            field=models.CharField(blank=True, default='', help_text='Brand / manufacturer, e.g. Square Pharmaceuticals', max_length=120),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='precautions',
            field=models.TextField(blank=True, default='', help_text='Precautions / warnings'),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='side_effects',
            field=models.TextField(blank=True, default='', help_text='Possible side effects'),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='usage_info',
            field=models.TextField(blank=True, default='', help_text='Usage instructions'),
        ),
        migrations.AlterField(
            model_name='medicineitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description on the card'),
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('urgency_note', models.TextField(blank=True, default='', help_text='Why it is needed urgently')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='core.medicineitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
