# Generated by Django 4.2.30 on 2026-08-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_medicine_item_pharmacy_fields_and_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='banner',
            field=models.ImageField(blank=True, help_text='Event banner / poster image (served from MEDIA_ROOT)', null=True, upload_to='club_events/banners/'),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='banner_url',
            field=models.CharField(blank=True, default='', help_text='Remote banner URL used when no image is uploaded', max_length=500),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this event on the student dashboard and public /clubs/ page'),
        ),
    ]
