# Generated by Django 4.2.30 on 2026-08-17 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_club_event_banner_and_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerequest',
            name='generic_name',
            field=models.CharField(blank=True, default='', help_text='Free-text generic name (e.g. Paracetamol)', max_length=200),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='medicine_name',
            field=models.CharField(blank=True, default='', help_text='Free-text medicine name for requests outside the catalog', max_length=200),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent Emergency')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Catalog match (empty for free-text requests without a match)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='core.medicineitem'),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
