# Generated by Django 4.2.30 on 2026-08-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_medicinerequest_generic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('study_corner', 'Study Corner'), ('research_ai', 'Research AI')], db_index=True, max_length=20)),
                ('source_type', models.CharField(help_text='Origin kind, e.g. "course_material" or "research_upload".', max_length=40)),
                ('source_id', models.CharField(help_text='Identifier of the source within its module (stringified).', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owning user for per-user scoping (Research AI); null when the document is shared (Study Corner).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vector_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['module', 'source_id'], name='core_vector_module_9070ae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vectordocument',
            constraint=models.UniqueConstraint(fields=('module', 'source_type', 'source_id'), name='uniq_vector_document_source'),
        ),
    ]
