# Generated by Django 4.2.30 on 2026-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_vectordocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Product photo — displayed on the store card and inventory grid', null=True, upload_to='pharmacy_products/'),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Product is available for purchase'),
        ),
        migrations.AddField(
            model_name='medicineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
