# Generated by Django 4.2.30 on 2026-08-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_medicineitem_image_medicineitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablepage',
            name='nav_icon',
            field=models.CharField(blank=True, default='file-lines', help_text="FontAwesome icon name for the nav pill (e.g. 'globe', 'book', 'flask')", max_length=50),
        ),
        migrations.AddField(
            model_name='editablepage',
            name='nav_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Sort order for the nav link (lower = left)'),
        ),
    ]
